### ISSUE TITLE
colloc examples stuck in case no collocations are found

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/wdglance#338]

**Comment by tomachalek** [comment]
this also applies for translation examples (the same tile logic)

**Comment by tomachalek** [comment]
@mzimandl  please test this one. In case you are not able to find a query producing result with no collocations/translations (I cannot recall any example myself) just fake it within a respective API (so it returns an empty array/whatever). There is a chance that the issue is not relevant any more. Thanks.

**Comment by mzimandl** [comment]
I tried it and it seems OK giving message that there are not enough data
