### ISSUE TITLE
Raw HTML tile

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/wdglance#368]
A new tile for loading raw HTML stuff from other resources. Typical use:
- attaching services with no machine-readable output (e.g. Wiktionary)
- adding specific auxiliary information to the page (either static or dynamic based on userId or actual query

The config should contain at least:

- apiURL:string
- maxTileHeight:string (= css unit, e.g. "20em").

Possible improvements:
- custom CSS (either via injected url or directly from the config as inline css)
- custom html subtree selection
- html sanitization, but here the responsibility is on administrators so they do not include e.g.
dynamic pages where users post their (unsafe) content.

**Comment by mzimandl** [comment]
Improvements in #390
