### ISSUE TITLE
New tile - compare words during time (SyD functionality)

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/wdglance#423]
Please see SyD's diachronic mode for more info. The chart should support any number of compared items (though it's quite debatable whether these 2+ variants are readable - see SyD again).

On the WaG side, a loose inspiration can be found in the TimeDistrib tile. But it is designed to deal with large corpora using chunked data loading so it can be also quite confusing - as this new tile probably won't need such a mode (i.e. we load all the data for each lemma at once).

Tip for the name: `MultiWordTimeDistrib` :)

**Comment by mzimandl** [comment]
Initial version done in #439
