### ISSUE TITLE
New tile - multi-word collocations

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/wdglance#424]
See SyD for more info (synchronic mode). At the moment its quite unclear how the visual representation should look like but the core logic of the tile should still be definable.

We should try to reuse at least the existing collocation API for KonText.

Because of the incomplete specification I would give this lower priority then #423.

**Comment by mzimandl** [comment]
collocation tile generalized in #455

**Comment by tomachalek** [comment]
:+1:
