### ISSUE TITLE
Concordance API for NoSkE

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/wdglance#573]
First of all:
1. install NoSkE into an LXC container (https://nlp.fi.muni.cz/trac/noske/wiki/Downloads). No need to compile anything - just use available deb files.
1. install some corpora (e.g. create a shared LXC directory just like in case of KonText development)
1. Once you have a working NoSkE container, please make a copy (e.g. tar --numeric-owner -czvf container noske.tar.gz ./path-to-container) for later reuse.
1. Analyze how NoSkE generates URLs for concordances and try to come up with a solution how to translate this into WaG
1. the api should be located in `src/js/common/api/noske/concordance.ts`

**Comment by mzimandl** [comment]
There is a documentation that might come in handy https://www.sketchengine.eu/documentation/methods-documentation/
