### ISSUE TITLE
WordForms tile - switching to the "alt" mode triggers an error

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/wdglance#623]

**Comment by mzimandl** [comment]
There is an error on line https://github.com/czcorpus/wdglance/blob/ee35f104b76fca2432235cc901aa1b9fa1c750a6/src/js/tiles/core/wordForms/views.tsx#L58

For some reason sort in `props.data.sort((x1, x2) => x2.freq - x1.freq)...` throws `TypeError: 0 is read-only` and component wont render. It works fine when I remove the sort part.

**Comment by tomachalek** [comment]
Probably caused by Immer.js which freezes the array (https://stackoverflow.com/questions/53420055/error-while-sorting-array-of-objects-cannot-assign-to-read-only-property-2-of/53420326). I've moved the sorting to the action reduce phase (where modifications are allowed) to prevent this.
